### ISSUE TITLE
Code crashes when moving camera

### ISSUE THREAD

**Issue by robtakefman** [google/helloargdx#3]
There is also a crash when moving away from area where plane was first placed.
1) Get the app to show plane
2) Move camera out of that view
3) come back and let it find the plane again, notice crash

01-23 09:54:42.027 29151-29176/com.github.claywilkinson.helloargdx E/AndroidRuntime: FATAL EXCEPTION: GLThread 5146
                                                                                     Process: com.github.claywilkinson.helloargdx, PID: 29151
                                                                                     java.nio.BufferOverflowException
                                                                                         at java.nio.Buffer.nextPutIndex(Buffer.java:508)
                                                                                         at java.nio.ByteBufferAsShortBuffer.put(ByteBufferAsShortBuffer.java:108)
                                                                                         at com.github.claywilkinson.helloargdx.PlaneModel.createPlane(PlaneModel.java:139)
                                                                                         at com.github.claywilkinson.helloargdx.HelloScene.drawPlanes(HelloScene.java:194)
                                                                                         at com.github.claywilkinson.helloargdx.HelloScene.render(HelloScene.java:103)
                                                                                         at com.github.claywilkinson.arcore.gdx.ARCoreScene.render(ARCoreScene.java:130)
                                                                                         at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:459)
                                                                                         at com.github.claywilkinson.arcore.gdx.ARCoreGraphics.onDrawFrame(ARCoreGraphics.java:68)
                                                                                         at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
                                                                                         at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)

**Comment by claywilkinson** [comment]
Thanks! I'll take a look.  Is does it consistently happen?

**Comment by nanaghartey** [comment]
Yup, I have the same problem. It keeps crashing when you move away from area where plane was first placed and return to find the plane again

**Comment by s1mar** [comment]
I am also facing this issue. Any pointers on where and what to look for, to fix this that is

**Comment by claywilkinson** [comment]
I could not reproduce it, but it looks like if the plane had less than 2 points in the polygon, it could cause this exception.  I added a check for that case.  Let me know if you can still reproduce it.
